#!/usr/bin/env bash
set -ex
# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python make_dataset.py class1_input.dat class1 ../results/class1_input.dat.pkl.gz
python run_deepneo.py class1 mhc ../results/class1_input.dat.pkl.gz ../results/class1_mhcbinding_result.txt
python run_deepneo.py class1 tcr ../results/class1_input.dat.pkl.gz ../results/class1_immunogenicity_result.txt